import tsconfigPaths from 'vite-tsconfig-paths';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [tsconfigPaths()],
  test: {
    globals: true,
    environment: 'node',
    fileParallelism: false,
    // Show console output for failing tests but stay quiet for passing ones.
    silent: 'passed-only',
    exclude: ['node_modules', 'dist', '.git', '.cache'],
    coverage: {
      // Requires @vitest/coverage-v8 (installed on first `aube test:coverage`).
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        'node_modules/',
        'dist/',
        'tests/',
        '**/*.config.ts',
        '**/*.types.ts',
        '**/*.queries.ts', // generated by pgtyped
        'src/instrument.ts',
      ],
      // TODO: set numeric thresholds once a baseline run establishes safe
      // floors, so coverage can't silently regress.
    },
  },
});
