import tsconfigPaths from 'vite-tsconfig-paths';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [tsconfigPaths()],
  test: {
    globals: true,
    environment: 'node',
    fileParallelism: false,
    // One shared PostGIS container for the whole integration run; each suite
    // clones a fresh database from a migrated template (see global-setup.ts).
    globalSetup: ['./tests/integration/global-setup.ts'],
    // Strip inherited config variables before every test file, so a developer
    // who has sourced .env runs the same suite as CI (see setup-env.ts).
    setupFiles: ['./tests/setup-env.ts'],
    // Show console output for failing tests but stay quiet for passing ones.
    silent: 'passed-only',
    exclude: ['node_modules', 'dist', '.git', '.cache'],
    coverage: {
      // Requires @vitest/coverage-v8 (installed on first `aube test:coverage`).
      provider: 'v8',
      // `clover` feeds the PR coverage report (danger-plugin-coverage); the
      // others are for local inspection.
      reporter: ['text', 'json', 'html', 'clover'],
      exclude: [
        'node_modules/',
        'dist/',
        'tests/',
        '**/*.config.ts',
        '**/*.types.ts',
        '**/*.queries.ts', // generated by pgtyped
        'src/instrument.ts',
      ],
      // Numeric thresholds are intentionally unset here: the coverage gate lives
      // in Danger (packages/danger/src/rules/coverage.ts), scoped to the files
      // changed in a PR, so we don't double-gate.
    },
  },
});
