import tsconfigPaths from 'vite-tsconfig-paths';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [tsconfigPaths()],
  test: {
    globals: true,
    environment: 'node',
    // Safe now that every suite clones its own database from the shared
    // template (global-setup.ts) and clears user data per test
    // (truncateUserData in tests/integration/auth.helpers.ts).
    fileParallelism: true,
    // The integration suites hit a real database and bcrypt (cost 10) twice per
    // sign-in; with several suites running at once that regularly exceeds
    // vitest's 5s/10s defaults, which showed up as sporadic "Test timed out"
    // failures that moved between files on every run.
    //
    // 30s was still too tight for the worst case under `--coverage`: v8
    // instrumentation stretches a hashing-bound flow roughly 15x, and
    // `should handle concurrent sign-in attempts` (five at once, serialized on
    // the CPU) lands near 30s on its own. Matched to hookTimeout so the
    // coverage job has real headroom instead of passing by a fraction of a
    // second.
    testTimeout: 60_000,
    hookTimeout: 60_000,
    // One shared PostGIS container for the whole integration run; each suite
    // clones a fresh database from a migrated template (see global-setup.ts).
    globalSetup: ['./tests/integration/global-setup.ts'],
    // Strip inherited config variables before every test file, so a developer
    // who has sourced .env runs the same suite as CI (see setup-env.ts).
    setupFiles: ['./tests/setup-env.ts'],
    // Show console output for failing tests but stay quiet for passing ones.
    silent: 'passed-only',
    exclude: ['node_modules', 'dist', '.git', '.cache'],
    coverage: {
      // Requires @vitest/coverage-v8 (installed on first `aube test:coverage`).
      provider: 'v8',
      // `clover` feeds the PR coverage report (danger-plugin-coverage); the
      // others are for local inspection.
      reporter: ['text', 'json', 'html', 'clover'],
      exclude: [
        'node_modules/',
        'dist/',
        'tests/',
        '**/*.config.ts',
        '**/*.types.ts',
        '**/*.queries.ts', // generated by pgtyped
        'src/**/*.test.ts',
        'src/instrument.ts',
      ],
      // Numeric thresholds are intentionally unset here: the coverage gate lives
      // in Danger (packages/danger/src/rules/coverage.ts), scoped to the files
      // changed in a PR, so we don't double-gate.
    },
  },
});
