import type { MigrationBuilder } from 'node-pg-migrate';

/**
 * Store ISO 3166-1 alpha-2 codes in the address country columns.
 *
 * The country selector used to write English names ("Germany"), and CardDAV
 * imports wrote whatever the client sent ("Deutschland", "USA"). The app now
 * stores codes ("DE") and translates them for display, so map every value we
 * can recognise to its code. Values that match no entry (free text such as a
 * typo) stay as they are; the address form asks for a country before it saves
 * such an address again.
 *
 * The mapping is a frozen copy: the old selector list
 * (apps/backend/src/utils/countries.ts), the old German alias map
 * (apps/backend/src/utils/country.ts) and the en/de names and aliases of
 * i18n-iso-countries 7.14.0. Migrations must not import app code, which
 * changes after this migration is written.
 *
 * The updated_at and change-log triggers are disabled during the bulk update:
 * they would change every CardDAV ETag and write a change-log row for each
 * address, for a change no user made.
 */

/** Lookup entries in priority order: the first entry for a (lowercased) name wins. */
const NAME_TO_CODE: ReadonlyArray<readonly [name: string, code: string]> = [
  ['AF', 'AF'],
  ['AL', 'AL'],
  ['DZ', 'DZ'],
  ['AS', 'AS'],
  ['AD', 'AD'],
  ['AO', 'AO'],
  ['AI', 'AI'],
  ['AQ', 'AQ'],
  ['AG', 'AG'],
  ['AR', 'AR'],
  ['AM', 'AM'],
  ['AW', 'AW'],
  ['AU', 'AU'],
  ['AT', 'AT'],
  ['AZ', 'AZ'],
  ['BS', 'BS'],
  ['BH', 'BH'],
  ['BD', 'BD'],
  ['BB', 'BB'],
  ['BY', 'BY'],
  ['BE', 'BE'],
  ['BZ', 'BZ'],
  ['BJ', 'BJ'],
  ['BM', 'BM'],
  ['BT', 'BT'],
  ['BO', 'BO'],
  ['BA', 'BA'],
  ['BW', 'BW'],
  ['BV', 'BV'],
  ['BR', 'BR'],
  ['IO', 'IO'],
  ['BN', 'BN'],
  ['BG', 'BG'],
  ['BF', 'BF'],
  ['BI', 'BI'],
  ['KH', 'KH'],
  ['CM', 'CM'],
  ['CA', 'CA'],
  ['CV', 'CV'],
  ['KY', 'KY'],
  ['CF', 'CF'],
  ['TD', 'TD'],
  ['CL', 'CL'],
  ['CN', 'CN'],
  ['CX', 'CX'],
  ['CC', 'CC'],
  ['CO', 'CO'],
  ['KM', 'KM'],
  ['CG', 'CG'],
  ['CD', 'CD'],
  ['CK', 'CK'],
  ['CR', 'CR'],
  ['CI', 'CI'],
  ['HR', 'HR'],
  ['CU', 'CU'],
  ['CY', 'CY'],
  ['CZ', 'CZ'],
  ['DK', 'DK'],
  ['DJ', 'DJ'],
  ['DM', 'DM'],
  ['DO', 'DO'],
  ['EC', 'EC'],
  ['EG', 'EG'],
  ['SV', 'SV'],
  ['GQ', 'GQ'],
  ['ER', 'ER'],
  ['EE', 'EE'],
  ['ET', 'ET'],
  ['FK', 'FK'],
  ['FO', 'FO'],
  ['FJ', 'FJ'],
  ['FI', 'FI'],
  ['FR', 'FR'],
  ['GF', 'GF'],
  ['PF', 'PF'],
  ['TF', 'TF'],
  ['GA', 'GA'],
  ['GM', 'GM'],
  ['GE', 'GE'],
  ['DE', 'DE'],
  ['GH', 'GH'],
  ['GI', 'GI'],
  ['GR', 'GR'],
  ['GL', 'GL'],
  ['GD', 'GD'],
  ['GP', 'GP'],
  ['GU', 'GU'],
  ['GT', 'GT'],
  ['GN', 'GN'],
  ['GW', 'GW'],
  ['GY', 'GY'],
  ['HT', 'HT'],
  ['HM', 'HM'],
  ['VA', 'VA'],
  ['HN', 'HN'],
  ['HK', 'HK'],
  ['HU', 'HU'],
  ['IS', 'IS'],
  ['IN', 'IN'],
  ['ID', 'ID'],
  ['IR', 'IR'],
  ['IQ', 'IQ'],
  ['IE', 'IE'],
  ['IL', 'IL'],
  ['IT', 'IT'],
  ['JM', 'JM'],
  ['JP', 'JP'],
  ['JO', 'JO'],
  ['KZ', 'KZ'],
  ['KE', 'KE'],
  ['KI', 'KI'],
  ['KP', 'KP'],
  ['KR', 'KR'],
  ['KW', 'KW'],
  ['KG', 'KG'],
  ['LA', 'LA'],
  ['LV', 'LV'],
  ['LB', 'LB'],
  ['LS', 'LS'],
  ['LR', 'LR'],
  ['LY', 'LY'],
  ['LI', 'LI'],
  ['LT', 'LT'],
  ['LU', 'LU'],
  ['MO', 'MO'],
  ['MG', 'MG'],
  ['MW', 'MW'],
  ['MY', 'MY'],
  ['MV', 'MV'],
  ['ML', 'ML'],
  ['MT', 'MT'],
  ['MH', 'MH'],
  ['MQ', 'MQ'],
  ['MR', 'MR'],
  ['MU', 'MU'],
  ['YT', 'YT'],
  ['MX', 'MX'],
  ['FM', 'FM'],
  ['MD', 'MD'],
  ['MC', 'MC'],
  ['MN', 'MN'],
  ['MS', 'MS'],
  ['MA', 'MA'],
  ['MZ', 'MZ'],
  ['MM', 'MM'],
  ['NA', 'NA'],
  ['NR', 'NR'],
  ['NP', 'NP'],
  ['NL', 'NL'],
  ['NC', 'NC'],
  ['NZ', 'NZ'],
  ['NI', 'NI'],
  ['NE', 'NE'],
  ['NG', 'NG'],
  ['NU', 'NU'],
  ['NF', 'NF'],
  ['MK', 'MK'],
  ['MP', 'MP'],
  ['NO', 'NO'],
  ['OM', 'OM'],
  ['PK', 'PK'],
  ['PW', 'PW'],
  ['PS', 'PS'],
  ['PA', 'PA'],
  ['PG', 'PG'],
  ['PY', 'PY'],
  ['PE', 'PE'],
  ['PH', 'PH'],
  ['PN', 'PN'],
  ['PL', 'PL'],
  ['PT', 'PT'],
  ['PR', 'PR'],
  ['QA', 'QA'],
  ['RE', 'RE'],
  ['RO', 'RO'],
  ['RU', 'RU'],
  ['RW', 'RW'],
  ['SH', 'SH'],
  ['KN', 'KN'],
  ['LC', 'LC'],
  ['PM', 'PM'],
  ['VC', 'VC'],
  ['WS', 'WS'],
  ['SM', 'SM'],
  ['ST', 'ST'],
  ['SA', 'SA'],
  ['SN', 'SN'],
  ['SC', 'SC'],
  ['SL', 'SL'],
  ['SG', 'SG'],
  ['SK', 'SK'],
  ['SI', 'SI'],
  ['SB', 'SB'],
  ['SO', 'SO'],
  ['ZA', 'ZA'],
  ['GS', 'GS'],
  ['ES', 'ES'],
  ['LK', 'LK'],
  ['SD', 'SD'],
  ['SR', 'SR'],
  ['SJ', 'SJ'],
  ['SZ', 'SZ'],
  ['SE', 'SE'],
  ['CH', 'CH'],
  ['SY', 'SY'],
  ['TW', 'TW'],
  ['TJ', 'TJ'],
  ['TZ', 'TZ'],
  ['TH', 'TH'],
  ['TL', 'TL'],
  ['TG', 'TG'],
  ['TK', 'TK'],
  ['TO', 'TO'],
  ['TT', 'TT'],
  ['TN', 'TN'],
  ['TR', 'TR'],
  ['TM', 'TM'],
  ['TC', 'TC'],
  ['TV', 'TV'],
  ['UG', 'UG'],
  ['UA', 'UA'],
  ['AE', 'AE'],
  ['GB', 'GB'],
  ['US', 'US'],
  ['UM', 'UM'],
  ['UY', 'UY'],
  ['UZ', 'UZ'],
  ['VU', 'VU'],
  ['VE', 'VE'],
  ['VN', 'VN'],
  ['VG', 'VG'],
  ['VI', 'VI'],
  ['WF', 'WF'],
  ['EH', 'EH'],
  ['YE', 'YE'],
  ['ZM', 'ZM'],
  ['ZW', 'ZW'],
  ['AX', 'AX'],
  ['BQ', 'BQ'],
  ['CW', 'CW'],
  ['GG', 'GG'],
  ['IM', 'IM'],
  ['JE', 'JE'],
  ['ME', 'ME'],
  ['BL', 'BL'],
  ['MF', 'MF'],
  ['RS', 'RS'],
  ['SX', 'SX'],
  ['SS', 'SS'],
  ['XK', 'XK'],
  ['Afghanistan', 'AF'],
  ['Albania', 'AL'],
  ['Algeria', 'DZ'],
  ['Andorra', 'AD'],
  ['Angola', 'AO'],
  ['Argentina', 'AR'],
  ['Armenia', 'AM'],
  ['Australia', 'AU'],
  ['Austria', 'AT'],
  ['Azerbaijan', 'AZ'],
  ['Bahrain', 'BH'],
  ['Bangladesh', 'BD'],
  ['Belarus', 'BY'],
  ['Belgium', 'BE'],
  ['Belize', 'BZ'],
  ['Benin', 'BJ'],
  ['Bhutan', 'BT'],
  ['Bolivia', 'BO'],
  ['Bosnia and Herzegovina', 'BA'],
  ['Botswana', 'BW'],
  ['Brazil', 'BR'],
  ['Brunei', 'BN'],
  ['Bulgaria', 'BG'],
  ['Burkina Faso', 'BF'],
  ['Burundi', 'BI'],
  ['Cambodia', 'KH'],
  ['Cameroon', 'CM'],
  ['Canada', 'CA'],
  ['Cape Verde', 'CV'],
  ['Central African Republic', 'CF'],
  ['Chad', 'TD'],
  ['Chile', 'CL'],
  ['China', 'CN'],
  ['Colombia', 'CO'],
  ['Congo', 'CG'],
  ['Costa Rica', 'CR'],
  ['Croatia', 'HR'],
  ['Cuba', 'CU'],
  ['Cyprus', 'CY'],
  ['Czech Republic', 'CZ'],
  ['Denmark', 'DK'],
  ['Djibouti', 'DJ'],
  ['Dominican Republic', 'DO'],
  ['Ecuador', 'EC'],
  ['Egypt', 'EG'],
  ['El Salvador', 'SV'],
  ['Estonia', 'EE'],
  ['Ethiopia', 'ET'],
  ['Finland', 'FI'],
  ['France', 'FR'],
  ['Gabon', 'GA'],
  ['Gambia', 'GM'],
  ['Georgia', 'GE'],
  ['Germany', 'DE'],
  ['Ghana', 'GH'],
  ['Greece', 'GR'],
  ['Guatemala', 'GT'],
  ['Guinea', 'GN'],
  ['Guyana', 'GY'],
  ['Haiti', 'HT'],
  ['Honduras', 'HN'],
  ['Hong Kong', 'HK'],
  ['Hungary', 'HU'],
  ['Iceland', 'IS'],
  ['India', 'IN'],
  ['Indonesia', 'ID'],
  ['Iran', 'IR'],
  ['Iraq', 'IQ'],
  ['Ireland', 'IE'],
  ['Israel', 'IL'],
  ['Italy', 'IT'],
  ['Jamaica', 'JM'],
  ['Japan', 'JP'],
  ['Jordan', 'JO'],
  ['Kazakhstan', 'KZ'],
  ['Kenya', 'KE'],
  ['South Korea', 'KR'],
  ['Kuwait', 'KW'],
  ['Kyrgyzstan', 'KG'],
  ['Laos', 'LA'],
  ['Latvia', 'LV'],
  ['Lebanon', 'LB'],
  ['Lesotho', 'LS'],
  ['Liberia', 'LR'],
  ['Libya', 'LY'],
  ['Liechtenstein', 'LI'],
  ['Lithuania', 'LT'],
  ['Luxembourg', 'LU'],
  ['North Macedonia', 'MK'],
  ['Madagascar', 'MG'],
  ['Malawi', 'MW'],
  ['Malaysia', 'MY'],
  ['Maldives', 'MV'],
  ['Mali', 'ML'],
  ['Malta', 'MT'],
  ['Mauritania', 'MR'],
  ['Mauritius', 'MU'],
  ['Mexico', 'MX'],
  ['Moldova', 'MD'],
  ['Monaco', 'MC'],
  ['Mongolia', 'MN'],
  ['Montenegro', 'ME'],
  ['Morocco', 'MA'],
  ['Mozambique', 'MZ'],
  ['Myanmar', 'MM'],
  ['Namibia', 'NA'],
  ['Nepal', 'NP'],
  ['Netherlands', 'NL'],
  ['New Zealand', 'NZ'],
  ['Nicaragua', 'NI'],
  ['Niger', 'NE'],
  ['Nigeria', 'NG'],
  ['Norway', 'NO'],
  ['Oman', 'OM'],
  ['Pakistan', 'PK'],
  ['Panama', 'PA'],
  ['Paraguay', 'PY'],
  ['Peru', 'PE'],
  ['Philippines', 'PH'],
  ['Poland', 'PL'],
  ['Portugal', 'PT'],
  ['Puerto Rico', 'PR'],
  ['Qatar', 'QA'],
  ['Romania', 'RO'],
  ['Russia', 'RU'],
  ['Rwanda', 'RW'],
  ['Saudi Arabia', 'SA'],
  ['Senegal', 'SN'],
  ['Serbia', 'RS'],
  ['Singapore', 'SG'],
  ['Slovakia', 'SK'],
  ['Slovenia', 'SI'],
  ['Somalia', 'SO'],
  ['South Africa', 'ZA'],
  ['Spain', 'ES'],
  ['Sri Lanka', 'LK'],
  ['Sudan', 'SD'],
  ['Suriname', 'SR'],
  ['Eswatini', 'SZ'],
  ['Sweden', 'SE'],
  ['Switzerland', 'CH'],
  ['Syria', 'SY'],
  ['Taiwan', 'TW'],
  ['Tajikistan', 'TJ'],
  ['Tanzania', 'TZ'],
  ['Thailand', 'TH'],
  ['Togo', 'TG'],
  ['Trinidad and Tobago', 'TT'],
  ['Tunisia', 'TN'],
  ['Turkey', 'TR'],
  ['Turkmenistan', 'TM'],
  ['Uganda', 'UG'],
  ['Ukraine', 'UA'],
  ['United Arab Emirates', 'AE'],
  ['United Kingdom', 'GB'],
  ['United States', 'US'],
  ['Uruguay', 'UY'],
  ['Uzbekistan', 'UZ'],
  ['Venezuela', 'VE'],
  ['Vietnam', 'VN'],
  ['Yemen', 'YE'],
  ['Zambia', 'ZM'],
  ['Zimbabwe', 'ZW'],
  ['deutschland', 'DE'],
  ['österreich', 'AT'],
  ['oesterreich', 'AT'],
  ['schweiz', 'CH'],
  ['frankreich', 'FR'],
  ['italien', 'IT'],
  ['spanien', 'ES'],
  ['niederlande', 'NL'],
  ['belgien', 'BE'],
  ['luxemburg', 'LU'],
  ['polen', 'PL'],
  ['tschechien', 'CZ'],
  ['dänemark', 'DK'],
  ['daenemark', 'DK'],
  ['vereinigtes königreich', 'GB'],
  ['großbritannien', 'GB'],
  ['grossbritannien', 'GB'],
  ['vereinigte staaten', 'US'],
  ['usa', 'US'],
  ['Afghanistan', 'AF'],
  ['Albania', 'AL'],
  ['Algeria', 'DZ'],
  ['American Samoa', 'AS'],
  ['Andorra', 'AD'],
  ['Angola', 'AO'],
  ['Anguilla', 'AI'],
  ['Antarctica', 'AQ'],
  ['Antigua and Barbuda', 'AG'],
  ['Argentina', 'AR'],
  ['Armenia', 'AM'],
  ['Aruba', 'AW'],
  ['Australia', 'AU'],
  ['Austria', 'AT'],
  ['Azerbaijan', 'AZ'],
  ['Bahamas', 'BS'],
  ['Bahrain', 'BH'],
  ['Bangladesh', 'BD'],
  ['Barbados', 'BB'],
  ['Belarus', 'BY'],
  ['Belgium', 'BE'],
  ['Belize', 'BZ'],
  ['Benin', 'BJ'],
  ['Bermuda', 'BM'],
  ['Bhutan', 'BT'],
  ['Bolivia', 'BO'],
  ['Bosnia and Herzegovina', 'BA'],
  ['Botswana', 'BW'],
  ['Bouvet Island', 'BV'],
  ['Brazil', 'BR'],
  ['British Indian Ocean Territory', 'IO'],
  ['Brunei Darussalam', 'BN'],
  ['Bulgaria', 'BG'],
  ['Burkina Faso', 'BF'],
  ['Burundi', 'BI'],
  ['Cambodia', 'KH'],
  ['Cameroon', 'CM'],
  ['Canada', 'CA'],
  ['Cape Verde', 'CV'],
  ['Cayman Islands', 'KY'],
  ['Central African Republic', 'CF'],
  ['Chad', 'TD'],
  ['Chile', 'CL'],
  ["People's Republic of China", 'CN'],
  ['China', 'CN'],
  ['Christmas Island', 'CX'],
  ['Cocos (Keeling) Islands', 'CC'],
  ['Colombia', 'CO'],
  ['Comoros', 'KM'],
  ['Republic of the Congo', 'CG'],
  ['Congo', 'CG'],
  ['Democratic Republic of the Congo', 'CD'],
  ['Congo', 'CD'],
  ['Cook Islands', 'CK'],
  ['Costa Rica', 'CR'],
  ["Cote d'Ivoire", 'CI'],
  ["Côte d'Ivoire", 'CI'],
  ['Ivory Coast', 'CI'],
  ['Croatia', 'HR'],
  ['Cuba', 'CU'],
  ['Cyprus', 'CY'],
  ['Czech Republic', 'CZ'],
  ['Czechia', 'CZ'],
  ['Denmark', 'DK'],
  ['Djibouti', 'DJ'],
  ['Dominica', 'DM'],
  ['Dominican Republic', 'DO'],
  ['Ecuador', 'EC'],
  ['Egypt', 'EG'],
  ['El Salvador', 'SV'],
  ['Equatorial Guinea', 'GQ'],
  ['Eritrea', 'ER'],
  ['Estonia', 'EE'],
  ['Ethiopia', 'ET'],
  ['Falkland Islands (Malvinas)', 'FK'],
  ['Faroe Islands', 'FO'],
  ['Fiji', 'FJ'],
  ['Finland', 'FI'],
  ['France', 'FR'],
  ['French Guiana', 'GF'],
  ['French Polynesia', 'PF'],
  ['French Southern Territories', 'TF'],
  ['Gabon', 'GA'],
  ['Republic of The Gambia', 'GM'],
  ['The Gambia', 'GM'],
  ['Gambia', 'GM'],
  ['Georgia', 'GE'],
  ['Germany', 'DE'],
  ['Ghana', 'GH'],
  ['Gibraltar', 'GI'],
  ['Greece', 'GR'],
  ['Greenland', 'GL'],
  ['Grenada', 'GD'],
  ['Guadeloupe', 'GP'],
  ['Guam', 'GU'],
  ['Guatemala', 'GT'],
  ['Guinea', 'GN'],
  ['Guinea-Bissau', 'GW'],
  ['Guyana', 'GY'],
  ['Haiti', 'HT'],
  ['Heard Island and McDonald Islands', 'HM'],
  ['Holy See (Vatican City State)', 'VA'],
  ['Honduras', 'HN'],
  ['Hong Kong', 'HK'],
  ['Hungary', 'HU'],
  ['Iceland', 'IS'],
  ['India', 'IN'],
  ['Indonesia', 'ID'],
  ['Islamic Republic of Iran', 'IR'],
  ['Iran', 'IR'],
  ['Iraq', 'IQ'],
  ['Ireland', 'IE'],
  ['Israel', 'IL'],
  ['Italy', 'IT'],
  ['Jamaica', 'JM'],
  ['Japan', 'JP'],
  ['Jordan', 'JO'],
  ['Kazakhstan', 'KZ'],
  ['Kenya', 'KE'],
  ['Kiribati', 'KI'],
  ['North Korea', 'KP'],
  ['South Korea', 'KR'],
  ['Korea, Republic of', 'KR'],
  ['Republic of Korea', 'KR'],
  ['Kuwait', 'KW'],
  ['Kyrgyzstan', 'KG'],
  ["Lao People's Democratic Republic", 'LA'],
  ['Latvia', 'LV'],
  ['Lebanon', 'LB'],
  ['Lesotho', 'LS'],
  ['Liberia', 'LR'],
  ['Libya', 'LY'],
  ['Liechtenstein', 'LI'],
  ['Lithuania', 'LT'],
  ['Luxembourg', 'LU'],
  ['Macao', 'MO'],
  ['Madagascar', 'MG'],
  ['Malawi', 'MW'],
  ['Malaysia', 'MY'],
  ['Maldives', 'MV'],
  ['Mali', 'ML'],
  ['Malta', 'MT'],
  ['Marshall Islands', 'MH'],
  ['Martinique', 'MQ'],
  ['Mauritania', 'MR'],
  ['Mauritius', 'MU'],
  ['Mayotte', 'YT'],
  ['Mexico', 'MX'],
  ['Micronesia, Federated States of', 'FM'],
  ['Moldova, Republic of', 'MD'],
  ['Monaco', 'MC'],
  ['Mongolia', 'MN'],
  ['Montserrat', 'MS'],
  ['Morocco', 'MA'],
  ['Mozambique', 'MZ'],
  ['Myanmar', 'MM'],
  ['Namibia', 'NA'],
  ['Nauru', 'NR'],
  ['Nepal', 'NP'],
  ['Netherlands', 'NL'],
  ['The Netherlands', 'NL'],
  ['Netherlands (Kingdom of the)', 'NL'],
  ['New Caledonia', 'NC'],
  ['New Zealand', 'NZ'],
  ['Nicaragua', 'NI'],
  ['Niger', 'NE'],
  ['Nigeria', 'NG'],
  ['Niue', 'NU'],
  ['Norfolk Island', 'NF'],
  ['The Republic of North Macedonia', 'MK'],
  ['North Macedonia', 'MK'],
  ['Northern Mariana Islands', 'MP'],
  ['Norway', 'NO'],
  ['Oman', 'OM'],
  ['Pakistan', 'PK'],
  ['Palau', 'PW'],
  ['State of Palestine', 'PS'],
  ['Palestine', 'PS'],
  ['Panama', 'PA'],
  ['Papua New Guinea', 'PG'],
  ['Paraguay', 'PY'],
  ['Peru', 'PE'],
  ['Philippines', 'PH'],
  ['Pitcairn', 'PN'],
  ['Pitcairn Islands', 'PN'],
  ['Poland', 'PL'],
  ['Portugal', 'PT'],
  ['Puerto Rico', 'PR'],
  ['Qatar', 'QA'],
  ['Reunion', 'RE'],
  ['Romania', 'RO'],
  ['Russian Federation', 'RU'],
  ['Russia', 'RU'],
  ['Rwanda', 'RW'],
  ['Saint Helena', 'SH'],
  ['Saint Kitts and Nevis', 'KN'],
  ['Saint Lucia', 'LC'],
  ['Saint Pierre and Miquelon', 'PM'],
  ['Saint Vincent and the Grenadines', 'VC'],
  ['Samoa', 'WS'],
  ['San Marino', 'SM'],
  ['Sao Tome and Principe', 'ST'],
  ['Saudi Arabia', 'SA'],
  ['Senegal', 'SN'],
  ['Seychelles', 'SC'],
  ['Sierra Leone', 'SL'],
  ['Singapore', 'SG'],
  ['Slovakia', 'SK'],
  ['Slovenia', 'SI'],
  ['Solomon Islands', 'SB'],
  ['Somalia', 'SO'],
  ['South Africa', 'ZA'],
  ['South Georgia and the South Sandwich Islands', 'GS'],
  ['Spain', 'ES'],
  ['Sri Lanka', 'LK'],
  ['Sudan', 'SD'],
  ['Suriname', 'SR'],
  ['Svalbard and Jan Mayen', 'SJ'],
  ['Eswatini', 'SZ'],
  ['Sweden', 'SE'],
  ['Switzerland', 'CH'],
  ['Syrian Arab Republic', 'SY'],
  ['Taiwan, Province of China', 'TW'],
  ['Taiwan', 'TW'],
  ['Tajikistan', 'TJ'],
  ['United Republic of Tanzania', 'TZ'],
  ['Tanzania', 'TZ'],
  ['Thailand', 'TH'],
  ['Timor-Leste', 'TL'],
  ['Togo', 'TG'],
  ['Tokelau', 'TK'],
  ['Tonga', 'TO'],
  ['Trinidad and Tobago', 'TT'],
  ['Tunisia', 'TN'],
  ['Türkiye', 'TR'],
  ['Turkey', 'TR'],
  ['Turkmenistan', 'TM'],
  ['Turks and Caicos Islands', 'TC'],
  ['Tuvalu', 'TV'],
  ['Uganda', 'UG'],
  ['Ukraine', 'UA'],
  ['United Arab Emirates', 'AE'],
  ['UAE', 'AE'],
  ['United Kingdom', 'GB'],
  ['UK', 'GB'],
  ['Great Britain', 'GB'],
  ['United States of America', 'US'],
  ['United States', 'US'],
  ['USA', 'US'],
  ['U.S.A.', 'US'],
  ['US', 'US'],
  ['U.S.', 'US'],
  ['United States Minor Outlying Islands', 'UM'],
  ['Uruguay', 'UY'],
  ['Uzbekistan', 'UZ'],
  ['Vanuatu', 'VU'],
  ['Venezuela', 'VE'],
  ['Vietnam', 'VN'],
  ['Virgin Islands, British', 'VG'],
  ['Virgin Islands, U.S.', 'VI'],
  ['Wallis and Futuna', 'WF'],
  ['Western Sahara', 'EH'],
  ['Yemen', 'YE'],
  ['Zambia', 'ZM'],
  ['Zimbabwe', 'ZW'],
  ['Åland Islands', 'AX'],
  ['Aland Islands', 'AX'],
  ['Bonaire, Sint Eustatius and Saba', 'BQ'],
  ['Curaçao', 'CW'],
  ['Guernsey', 'GG'],
  ['Isle of Man', 'IM'],
  ['Jersey', 'JE'],
  ['Montenegro', 'ME'],
  ['Saint Barthélemy', 'BL'],
  ['Saint Martin (French part)', 'MF'],
  ['Serbia', 'RS'],
  ['Sint Maarten (Dutch part)', 'SX'],
  ['South Sudan', 'SS'],
  ['Kosovo', 'XK'],
  ['Afghanistan', 'AF'],
  ['Ägypten', 'EG'],
  ['Åland', 'AX'],
  ['Albanien', 'AL'],
  ['Algerien', 'DZ'],
  ['Amerikanisch-Samoa', 'AS'],
  ['Amerikanische Jungferninseln', 'VI'],
  ['Andorra', 'AD'],
  ['Angola', 'AO'],
  ['Anguilla', 'AI'],
  ['Antarktis', 'AQ'],
  ['Antigua und Barbuda', 'AG'],
  ['Äquatorialguinea', 'GQ'],
  ['Argentinien', 'AR'],
  ['Armenien', 'AM'],
  ['Aruba', 'AW'],
  ['Aserbaidschan', 'AZ'],
  ['Äthiopien', 'ET'],
  ['Australien', 'AU'],
  ['Bahamas', 'BS'],
  ['Bahrain', 'BH'],
  ['Bangladesch', 'BD'],
  ['Barbados', 'BB'],
  ['Belarus', 'BY'],
  ['Belgien', 'BE'],
  ['Belize', 'BZ'],
  ['Benin', 'BJ'],
  ['Bermuda', 'BM'],
  ['Bhutan', 'BT'],
  ['Bolivien', 'BO'],
  ['Bonaire', 'BQ'],
  ['Bosnien und Herzegowina', 'BA'],
  ['Botswana', 'BW'],
  ['Bouvetinsel', 'BV'],
  ['Brasilien', 'BR'],
  ['Britische Jungferninseln', 'VG'],
  ['Britisches Territorium im Indischen Ozean', 'IO'],
  ['Brunei Darussalam', 'BN'],
  ['Bulgarien', 'BG'],
  ['Burkina Faso', 'BF'],
  ['Burundi', 'BI'],
  ['Chile', 'CL'],
  ['China', 'CN'],
  ['Cookinseln', 'CK'],
  ['Costa Rica', 'CR'],
  ['Elfenbeinküste', 'CI'],
  ['Curaçao', 'CW'],
  ['Dänemark', 'DK'],
  ['Deutschland', 'DE'],
  ['Dominica', 'DM'],
  ['Dominikanische Republik', 'DO'],
  ['Dschibuti', 'DJ'],
  ['Ecuador', 'EC'],
  ['El Salvador', 'SV'],
  ['Eritrea', 'ER'],
  ['Estland', 'EE'],
  ['Falklandinseln', 'FK'],
  ['Färöer', 'FO'],
  ['Fidschi', 'FJ'],
  ['Finnland', 'FI'],
  ['Frankreich', 'FR'],
  ['Französisch-Guayana', 'GF'],
  ['Französisch-Polynesien', 'PF'],
  ['Französische Süd- und Antarktisgebiete', 'TF'],
  ['Gabun', 'GA'],
  ['Gambia', 'GM'],
  ['Georgien', 'GE'],
  ['Ghana', 'GH'],
  ['Gibraltar', 'GI'],
  ['Grenada', 'GD'],
  ['Griechenland', 'GR'],
  ['Grönland', 'GL'],
  ['Guadeloupe', 'GP'],
  ['Guam', 'GU'],
  ['Guatemala', 'GT'],
  ['Guernsey', 'GG'],
  ['Guinea', 'GN'],
  ['Guinea-Bissau', 'GW'],
  ['Guyana', 'GY'],
  ['Haiti', 'HT'],
  ['Heard und McDonaldinseln', 'HM'],
  ['Honduras', 'HN'],
  ['Hongkong', 'HK'],
  ['Hong Kong', 'HK'],
  ['Indien', 'IN'],
  ['Indonesien', 'ID'],
  ['Insel Man', 'IM'],
  ['Irak', 'IQ'],
  ['Iran', 'IR'],
  ['Irland', 'IE'],
  ['Island', 'IS'],
  ['Israel', 'IL'],
  ['Italien', 'IT'],
  ['Jamaika', 'JM'],
  ['Japan', 'JP'],
  ['Jemen', 'YE'],
  ['Jersey', 'JE'],
  ['Jordanien', 'JO'],
  ['Kaimaninseln', 'KY'],
  ['Kambodscha', 'KH'],
  ['Kamerun', 'CM'],
  ['Kanada', 'CA'],
  ['Kap Verde', 'CV'],
  ['Kasachstan', 'KZ'],
  ['Katar', 'QA'],
  ['Kenia', 'KE'],
  ['Kirgisistan', 'KG'],
  ['Kiribati', 'KI'],
  ['Kokosinseln', 'CC'],
  ['Kolumbien', 'CO'],
  ['Komoren', 'KM'],
  ['Kongo', 'CD'],
  ['Nordkorea', 'KP'],
  ['Südkorea', 'KR'],
  ['Kroatien', 'HR'],
  ['Kuba', 'CU'],
  ['Kuwait', 'KW'],
  ['Laos', 'LA'],
  ['Lesotho', 'LS'],
  ['Lettland', 'LV'],
  ['Libanon', 'LB'],
  ['Liberia', 'LR'],
  ['Libyen', 'LY'],
  ['Liechtenstein', 'LI'],
  ['Litauen', 'LT'],
  ['Luxemburg', 'LU'],
  ['Macao', 'MO'],
  ['Madagaskar', 'MG'],
  ['Malawi', 'MW'],
  ['Malaysia', 'MY'],
  ['Malediven', 'MV'],
  ['Mali', 'ML'],
  ['Malta', 'MT'],
  ['Marokko', 'MA'],
  ['Marshallinseln', 'MH'],
  ['Martinique', 'MQ'],
  ['Mauretanien', 'MR'],
  ['Mauritius', 'MU'],
  ['Mayotte', 'YT'],
  ['Mexiko', 'MX'],
  ['Mikronesien', 'FM'],
  ['Moldawien', 'MD'],
  ['Monaco', 'MC'],
  ['Mongolei', 'MN'],
  ['Montenegro', 'ME'],
  ['Montserrat', 'MS'],
  ['Mosambik', 'MZ'],
  ['Myanmar', 'MM'],
  ['Namibia', 'NA'],
  ['Nauru', 'NR'],
  ['Nepal', 'NP'],
  ['Neukaledonien', 'NC'],
  ['Neuseeland', 'NZ'],
  ['Nicaragua', 'NI'],
  ['Niederlande', 'NL'],
  ['Niger', 'NE'],
  ['Nigeria', 'NG'],
  ['Niue', 'NU'],
  ['Nordmazedonien', 'MK'],
  ['Nördliche Marianen', 'MP'],
  ['Norfolkinsel', 'NF'],
  ['Norwegen', 'NO'],
  ['Oman', 'OM'],
  ['Österreich', 'AT'],
  ['Osttimor', 'TL'],
  ['Pakistan', 'PK'],
  ['Staat Palästina', 'PS'],
  ['Palau', 'PW'],
  ['Panama', 'PA'],
  ['Papua-Neuguinea', 'PG'],
  ['Paraguay', 'PY'],
  ['Peru', 'PE'],
  ['Philippinen', 'PH'],
  ['Pitcairninseln', 'PN'],
  ['Polen', 'PL'],
  ['Portugal', 'PT'],
  ['Puerto Rico', 'PR'],
  ['Taiwan', 'TW'],
  ['Republik Kongo', 'CG'],
  ['Réunion', 'RE'],
  ['Ruanda', 'RW'],
  ['Rumänien', 'RO'],
  ['Russische Föderation', 'RU'],
  ['Russland', 'RU'],
  ['Saint-Barthélemy', 'BL'],
  ['Saint-Martin', 'MF'],
  ['Salomonen', 'SB'],
  ['Sambia', 'ZM'],
  ['Samoa', 'WS'],
  ['San Marino', 'SM'],
  ['São Tomé und Príncipe', 'ST'],
  ['Saudi-Arabien', 'SA'],
  ['Schweden', 'SE'],
  ['Schweiz', 'CH'],
  ['Senegal', 'SN'],
  ['Serbien', 'RS'],
  ['Seychellen', 'SC'],
  ['Sierra Leone', 'SL'],
  ['Simbabwe', 'ZW'],
  ['Singapur', 'SG'],
  ['Sint Maarten', 'SX'],
  ['Slowakei', 'SK'],
  ['Slowenien', 'SI'],
  ['Somalia', 'SO'],
  ['Spanien', 'ES'],
  ['Sri Lanka', 'LK'],
  ['St. Helena', 'SH'],
  ['St. Kitts und Nevis', 'KN'],
  ['St. Lucia', 'LC'],
  ['Saint-Pierre und Miquelon', 'PM'],
  ['St. Vincent und die Grenadinen', 'VC'],
  ['Südafrika', 'ZA'],
  ['Sudan', 'SD'],
  ['Südgeorgien und die Südlichen Sandwichinseln', 'GS'],
  ['Südsudan', 'SS'],
  ['Suriname', 'SR'],
  ['Svalbard und Jan Mayen', 'SJ'],
  ['Eswatini', 'SZ'],
  ['Syrien, Arabische Republik', 'SY'],
  ['Tadschikistan', 'TJ'],
  ['Tansania, Vereinigte Republik', 'TZ'],
  ['Tansania', 'TZ'],
  ['Thailand', 'TH'],
  ['Togo', 'TG'],
  ['Tokelau', 'TK'],
  ['Tonga', 'TO'],
  ['Trinidad und Tobago', 'TT'],
  ['Tschad', 'TD'],
  ['Tschechische Republik', 'CZ'],
  ['Tschechien', 'CZ'],
  ['Tunesien', 'TN'],
  ['Türkei', 'TR'],
  ['Turkmenistan', 'TM'],
  ['Turks- und Caicosinseln', 'TC'],
  ['Tuvalu', 'TV'],
  ['Uganda', 'UG'],
  ['Ukraine', 'UA'],
  ['Ungarn', 'HU'],
  ['United States Minor Outlying Islands', 'UM'],
  ['Uruguay', 'UY'],
  ['Usbekistan', 'UZ'],
  ['Vanuatu', 'VU'],
  ['Vatikanstadt', 'VA'],
  ['Venezuela', 'VE'],
  ['Vereinigte Arabische Emirate', 'AE'],
  ['Vereinigte Staaten von Amerika', 'US'],
  ['Vereinigte Staaten', 'US'],
  ['USA', 'US'],
  ['Vereinigtes Königreich', 'GB'],
  ['Großbritannien', 'GB'],
  ['Vietnam', 'VN'],
  ['Wallis und Futuna', 'WF'],
  ['Weihnachtsinsel', 'CX'],
  ['Westsahara', 'EH'],
  ['Zentralafrikanische Republik', 'CF'],
  ['Zypern', 'CY'],
  ['Kosovo', 'XK'],
];

/** Name written back by down(): the old selector name, else the English official name. */
const CODE_TO_NAME: ReadonlyArray<readonly [code: string, name: string]> = [
  ['AF', 'Afghanistan'],
  ['AL', 'Albania'],
  ['DZ', 'Algeria'],
  ['AS', 'American Samoa'],
  ['AD', 'Andorra'],
  ['AO', 'Angola'],
  ['AI', 'Anguilla'],
  ['AQ', 'Antarctica'],
  ['AG', 'Antigua and Barbuda'],
  ['AR', 'Argentina'],
  ['AM', 'Armenia'],
  ['AW', 'Aruba'],
  ['AU', 'Australia'],
  ['AT', 'Austria'],
  ['AZ', 'Azerbaijan'],
  ['BS', 'Bahamas'],
  ['BH', 'Bahrain'],
  ['BD', 'Bangladesh'],
  ['BB', 'Barbados'],
  ['BY', 'Belarus'],
  ['BE', 'Belgium'],
  ['BZ', 'Belize'],
  ['BJ', 'Benin'],
  ['BM', 'Bermuda'],
  ['BT', 'Bhutan'],
  ['BO', 'Bolivia'],
  ['BA', 'Bosnia and Herzegovina'],
  ['BW', 'Botswana'],
  ['BV', 'Bouvet Island'],
  ['BR', 'Brazil'],
  ['IO', 'British Indian Ocean Territory'],
  ['BN', 'Brunei'],
  ['BG', 'Bulgaria'],
  ['BF', 'Burkina Faso'],
  ['BI', 'Burundi'],
  ['KH', 'Cambodia'],
  ['CM', 'Cameroon'],
  ['CA', 'Canada'],
  ['CV', 'Cape Verde'],
  ['KY', 'Cayman Islands'],
  ['CF', 'Central African Republic'],
  ['TD', 'Chad'],
  ['CL', 'Chile'],
  ['CN', 'China'],
  ['CX', 'Christmas Island'],
  ['CC', 'Cocos (Keeling) Islands'],
  ['CO', 'Colombia'],
  ['KM', 'Comoros'],
  ['CG', 'Congo'],
  ['CD', 'Democratic Republic of the Congo'],
  ['CK', 'Cook Islands'],
  ['CR', 'Costa Rica'],
  ['CI', "Cote d'Ivoire"],
  ['HR', 'Croatia'],
  ['CU', 'Cuba'],
  ['CY', 'Cyprus'],
  ['CZ', 'Czech Republic'],
  ['DK', 'Denmark'],
  ['DJ', 'Djibouti'],
  ['DM', 'Dominica'],
  ['DO', 'Dominican Republic'],
  ['EC', 'Ecuador'],
  ['EG', 'Egypt'],
  ['SV', 'El Salvador'],
  ['GQ', 'Equatorial Guinea'],
  ['ER', 'Eritrea'],
  ['EE', 'Estonia'],
  ['ET', 'Ethiopia'],
  ['FK', 'Falkland Islands (Malvinas)'],
  ['FO', 'Faroe Islands'],
  ['FJ', 'Fiji'],
  ['FI', 'Finland'],
  ['FR', 'France'],
  ['GF', 'French Guiana'],
  ['PF', 'French Polynesia'],
  ['TF', 'French Southern Territories'],
  ['GA', 'Gabon'],
  ['GM', 'Gambia'],
  ['GE', 'Georgia'],
  ['DE', 'Germany'],
  ['GH', 'Ghana'],
  ['GI', 'Gibraltar'],
  ['GR', 'Greece'],
  ['GL', 'Greenland'],
  ['GD', 'Grenada'],
  ['GP', 'Guadeloupe'],
  ['GU', 'Guam'],
  ['GT', 'Guatemala'],
  ['GN', 'Guinea'],
  ['GW', 'Guinea-Bissau'],
  ['GY', 'Guyana'],
  ['HT', 'Haiti'],
  ['HM', 'Heard Island and McDonald Islands'],
  ['VA', 'Holy See (Vatican City State)'],
  ['HN', 'Honduras'],
  ['HK', 'Hong Kong'],
  ['HU', 'Hungary'],
  ['IS', 'Iceland'],
  ['IN', 'India'],
  ['ID', 'Indonesia'],
  ['IR', 'Iran'],
  ['IQ', 'Iraq'],
  ['IE', 'Ireland'],
  ['IL', 'Israel'],
  ['IT', 'Italy'],
  ['JM', 'Jamaica'],
  ['JP', 'Japan'],
  ['JO', 'Jordan'],
  ['KZ', 'Kazakhstan'],
  ['KE', 'Kenya'],
  ['KI', 'Kiribati'],
  ['KP', 'North Korea'],
  ['KR', 'South Korea'],
  ['KW', 'Kuwait'],
  ['KG', 'Kyrgyzstan'],
  ['LA', 'Laos'],
  ['LV', 'Latvia'],
  ['LB', 'Lebanon'],
  ['LS', 'Lesotho'],
  ['LR', 'Liberia'],
  ['LY', 'Libya'],
  ['LI', 'Liechtenstein'],
  ['LT', 'Lithuania'],
  ['LU', 'Luxembourg'],
  ['MO', 'Macao'],
  ['MG', 'Madagascar'],
  ['MW', 'Malawi'],
  ['MY', 'Malaysia'],
  ['MV', 'Maldives'],
  ['ML', 'Mali'],
  ['MT', 'Malta'],
  ['MH', 'Marshall Islands'],
  ['MQ', 'Martinique'],
  ['MR', 'Mauritania'],
  ['MU', 'Mauritius'],
  ['YT', 'Mayotte'],
  ['MX', 'Mexico'],
  ['FM', 'Micronesia, Federated States of'],
  ['MD', 'Moldova'],
  ['MC', 'Monaco'],
  ['MN', 'Mongolia'],
  ['MS', 'Montserrat'],
  ['MA', 'Morocco'],
  ['MZ', 'Mozambique'],
  ['MM', 'Myanmar'],
  ['NA', 'Namibia'],
  ['NR', 'Nauru'],
  ['NP', 'Nepal'],
  ['NL', 'Netherlands'],
  ['NC', 'New Caledonia'],
  ['NZ', 'New Zealand'],
  ['NI', 'Nicaragua'],
  ['NE', 'Niger'],
  ['NG', 'Nigeria'],
  ['NU', 'Niue'],
  ['NF', 'Norfolk Island'],
  ['MK', 'North Macedonia'],
  ['MP', 'Northern Mariana Islands'],
  ['NO', 'Norway'],
  ['OM', 'Oman'],
  ['PK', 'Pakistan'],
  ['PW', 'Palau'],
  ['PS', 'State of Palestine'],
  ['PA', 'Panama'],
  ['PG', 'Papua New Guinea'],
  ['PY', 'Paraguay'],
  ['PE', 'Peru'],
  ['PH', 'Philippines'],
  ['PN', 'Pitcairn'],
  ['PL', 'Poland'],
  ['PT', 'Portugal'],
  ['PR', 'Puerto Rico'],
  ['QA', 'Qatar'],
  ['RE', 'Reunion'],
  ['RO', 'Romania'],
  ['RU', 'Russia'],
  ['RW', 'Rwanda'],
  ['SH', 'Saint Helena'],
  ['KN', 'Saint Kitts and Nevis'],
  ['LC', 'Saint Lucia'],
  ['PM', 'Saint Pierre and Miquelon'],
  ['VC', 'Saint Vincent and the Grenadines'],
  ['WS', 'Samoa'],
  ['SM', 'San Marino'],
  ['ST', 'Sao Tome and Principe'],
  ['SA', 'Saudi Arabia'],
  ['SN', 'Senegal'],
  ['SC', 'Seychelles'],
  ['SL', 'Sierra Leone'],
  ['SG', 'Singapore'],
  ['SK', 'Slovakia'],
  ['SI', 'Slovenia'],
  ['SB', 'Solomon Islands'],
  ['SO', 'Somalia'],
  ['ZA', 'South Africa'],
  ['GS', 'South Georgia and the South Sandwich Islands'],
  ['ES', 'Spain'],
  ['LK', 'Sri Lanka'],
  ['SD', 'Sudan'],
  ['SR', 'Suriname'],
  ['SJ', 'Svalbard and Jan Mayen'],
  ['SZ', 'Eswatini'],
  ['SE', 'Sweden'],
  ['CH', 'Switzerland'],
  ['SY', 'Syria'],
  ['TW', 'Taiwan'],
  ['TJ', 'Tajikistan'],
  ['TZ', 'Tanzania'],
  ['TH', 'Thailand'],
  ['TL', 'Timor-Leste'],
  ['TG', 'Togo'],
  ['TK', 'Tokelau'],
  ['TO', 'Tonga'],
  ['TT', 'Trinidad and Tobago'],
  ['TN', 'Tunisia'],
  ['TR', 'Turkey'],
  ['TM', 'Turkmenistan'],
  ['TC', 'Turks and Caicos Islands'],
  ['TV', 'Tuvalu'],
  ['UG', 'Uganda'],
  ['UA', 'Ukraine'],
  ['AE', 'United Arab Emirates'],
  ['GB', 'United Kingdom'],
  ['US', 'United States'],
  ['UM', 'United States Minor Outlying Islands'],
  ['UY', 'Uruguay'],
  ['UZ', 'Uzbekistan'],
  ['VU', 'Vanuatu'],
  ['VE', 'Venezuela'],
  ['VN', 'Vietnam'],
  ['VG', 'Virgin Islands, British'],
  ['VI', 'Virgin Islands, U.S.'],
  ['WF', 'Wallis and Futuna'],
  ['EH', 'Western Sahara'],
  ['YE', 'Yemen'],
  ['ZM', 'Zambia'],
  ['ZW', 'Zimbabwe'],
  ['AX', 'Åland Islands'],
  ['BQ', 'Bonaire, Sint Eustatius and Saba'],
  ['CW', 'Curaçao'],
  ['GG', 'Guernsey'],
  ['IM', 'Isle of Man'],
  ['JE', 'Jersey'],
  ['ME', 'Montenegro'],
  ['BL', 'Saint Barthélemy'],
  ['MF', 'Saint Martin (French part)'],
  ['RS', 'Serbia'],
  ['SX', 'Sint Maarten (Dutch part)'],
  ['SS', 'South Sudan'],
  ['XK', 'Kosovo'],
];

const TARGETS: ReadonlyArray<{ table: string; column: string; triggers: readonly string[] }> = [
  {
    table: 'friends.friend_addresses',
    column: 'country',
    triggers: ['update_friend_addresses_updated_at', 'address_change_trigger'],
  },
  {
    table: 'collectives.collective_addresses',
    column: 'country',
    triggers: ['update_collective_addresses_updated_at'],
  },
  {
    table: 'collectives.collectives',
    column: 'address_country',
    triggers: ['update_collectives_updated_at'],
  },
];

const literal = (value: string) => `'${value.replaceAll("'", "''")}'`;

/** Run `statements` for `table` with its updated_at and change-log triggers disabled. */
function withoutTriggers(table: string, triggers: readonly string[], statements: string): string {
  const toggle = (action: 'DISABLE' | 'ENABLE') =>
    triggers.map((trigger) => `ALTER TABLE ${table} ${action} TRIGGER ${trigger};`).join('\n');
  return [toggle('DISABLE'), statements, toggle('ENABLE')].join('\n');
}

export async function up(pgm: MigrationBuilder): Promise<void> {
  const values = NAME_TO_CODE.map(
    ([name, code]) => `(lower(${literal(name)}), ${literal(code)})`,
  ).join(',\n');
  pgm.sql(`
    CREATE TEMP TABLE country_name_map (name text PRIMARY KEY, code text NOT NULL) ON COMMIT DROP;
    INSERT INTO country_name_map (name, code) VALUES
    ${values}
    ON CONFLICT (name) DO NOTHING;
  `);

  for (const { table, column, triggers } of TARGETS) {
    pgm.sql(
      withoutTriggers(
        table,
        triggers,
        `
        UPDATE ${table} SET ${column} = NULL WHERE ${column} IS NOT NULL AND btrim(${column}) = '';
        UPDATE ${table} AS t SET ${column} = m.code
          FROM country_name_map m
          WHERE lower(btrim(t.${column})) = m.name AND t.${column} IS DISTINCT FROM m.code;
        `,
      ),
    );
  }
}

export async function down(pgm: MigrationBuilder): Promise<void> {
  const values = CODE_TO_NAME.map(([code, name]) => `(${literal(code)}, ${literal(name)})`).join(
    ',\n',
  );
  for (const { table, column, triggers } of TARGETS) {
    pgm.sql(
      withoutTriggers(
        table,
        triggers,
        `
        UPDATE ${table} AS t SET ${column} = m.name
          FROM (VALUES ${values}) AS m(code, name)
          WHERE t.${column} = m.code;
        `,
      ),
    );
  }
}
